platform :ios, '11.0'
def capacitor_pods
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Plugin' do
  use_frameworks!
  capacitor_pods
  pod 'TTLock'

end

target 'PluginTests' do
  capacitor_pods
end